### ISSUE TITLE
Uploading binary large files to HDFS

### ISSUE THREAD

**Issue by JoelMiller74** [bamcisnetworks/HDFS#1]
Thank you for creating this module. So far, I have been able to create sessions, get files and data, and wriet files. However, ultimately, what I am trying to accomplish is to upload large binary files (SQL Backups) to HDFS. It appears that this code only allows uploading text.
Is that assumption correct? Is there any way to upload a large binary file from my computer or is this for text only.
Thanks!

**Comment by hakenmt** [comment]
So I originally wrote this for the purpose of sending objects through the pipeline (and serializing as json) or standard csv, etc type file content to the cmdlet for writing to HDFS. However, I don't think there's a reason why I couldn't modify the cmdlet to accept a file path as input and read the file as bytes to send to HDFS. I'll need to do a little research to get the http syntax right, but should be doable.

**Comment by JoelMiller74** [comment]
Thank you very much! I was not expecting such a quick and helpful response! 

If you know how that could be added I would be eternally grateful. I really appreciate your willingness to assist and for placing this out here for others to use.

**Comment by hakenmt** [comment]
I've published a new version of the module, v1.0.0.2. It includes an `-InputFile` parameter for New-HDFSItem which will read a file as bytes and store in HDFS verbatim. When you do Get-HDFSContent the default is to read back as a byte array unless you specify an encoding. Please give it a try and let me know if that does what you need.

**Comment by JoelMiller74** [comment]
Thank you very much. In the meantime, I had tried a few things to see if I could get it working. I was successful but my approach was just slightly different.
When I tried your new 1.0.0.2 version, I received the following:
```
New-HDFSSession -Namenode HDFSMasterNode
New-HDFSItem -InputFile "c:\apex\testbackup.bak" -Path "
/testDatabases/issueTest/1821/other/testbackup16.bak" -Verbose -Session HDFSMasterNode
```
```
VERBOSE: PUT http://HDFSMasterNode:50070/webhdfs/v1/testDatabases/issueTest/1821/other/testbackup16.bak?op=CREATE with
0-byte payload
VERBOSE: received 0-byte response of content type application/octet-stream
VERBOSE: Redirect location:
http://HDFSslave18:50075/webhdfs/v1/testDatabases/issueTest/1821/other/testbackup16.bak?op=CREATE&namenoderpcaddress=n
ameservice1&overwrite=false
VERBOSE: PUT
http://HDFSslave18:50075/webhdfs/v1/testDatabases/issueTest/1821/other/testbackup16.bak?op=CREATE&namenoderpcaddress=n
ameservice1&overwrite=false with -1-byte payload
WARNING: There was an issue creating the item: 403 Forbidden The remote server returned an error: (403) Forbidden.
 -
```
The only change that was different in my approach was that if I saw that the InputFile parameter is set, I use a parameter on Invoke-WebRequest of -InFile. When I do that, I am not getting the 403 forbidden error. That also creates a stream and presents a status bar.
Are you also receiving a 403 forbidden error or is it working when you try it.
Do you have any opinion on which approach might work better overall or why I may be getting a  403 error?
The only change I had (basically) was not using a stream and just specifying the upload as:
`[Microsoft.PowerShell.Commands.WebResponseObject]$Result = Invoke-WebRequest -Uri $Location -Method Put -ErrorAction Stop -WebSession $SessionInfo.Session -InFile $InputFile`

Thanks!

**Comment by hakenmt** [comment]
It worked when in my tests. You may receive a 403 error if the file already exists and you don't specify `-Overwrite`. To be honest, I forgot about the `-InFile` parameter on `Invoke-WebRequest`. I'll update the cmdlet to use that, just need to run a few tests.

**Comment by hakenmt** [comment]
Alright, give it a try now with version 1.0.0.3.
